package httpapi

import (
	"net/http"

	appsqlite "nsx-t-mockapi/internal/sqlite"
)

func (r *router) managerRoutes() []Route {
	return []Route{
		{
			Name:        "manager.search.query",
			Method:      http.MethodGet,
			Template:    "/api/v1/search/query",
			Handler:     r.handleSearchQuery(),
			RequireAuth: true,
		},
		{
			Name:        "manager.search.dsl",
			Method:      http.MethodGet,
			Template:    "/api/v1/search/dsl",
			Handler:     r.handleSearch(appsqlite.SearchSyntaxDSL),
			RequireAuth: true,
		},
		{
			Name:        "manager.firewall.sections.list",
			Method:      http.MethodGet,
			Template:    managerFirewallSectionsRouteTemplate,
			Handler:     r.handleManagerFirewallSectionList(),
			RequireAuth: true,
		},
		{
			Name:        "manager.firewall.sections.create",
			Method:      http.MethodPost,
			Template:    managerFirewallSectionsRouteTemplate,
			Handler:     r.handleManagerFirewallSectionCreate(),
			RequireAuth: true,
		},
		{
			Name:        "manager.firewall.sections.create_with_rules",
			Method:      http.MethodPost,
			Template:    managerFirewallSectionsRouteTemplate,
			Action:      "create_with_rules",
			Handler:     r.handleManagerFirewallSectionCreateWithRules(),
			RequireAuth: true,
		},
		{
			Name:        "manager.firewall.sections.get",
			Method:      http.MethodGet,
			Template:    managerFirewallSectionItemRouteTemplate,
			Handler:     r.handleManagerFirewallSectionGet(),
			RequireAuth: true,
		},
		{
			Name:        "manager.firewall.sections.update",
			Method:      http.MethodPut,
			Template:    managerFirewallSectionItemRouteTemplate,
			Handler:     r.handleManagerFirewallSectionUpdate(),
			RequireAuth: true,
		},
		{
			Name:        "manager.firewall.sections.delete",
			Method:      http.MethodDelete,
			Template:    managerFirewallSectionItemRouteTemplate,
			Handler:     r.handleManagerFirewallSectionDelete(),
			RequireAuth: true,
		},
		{
			Name:        "manager.firewall.sections.revise",
			Method:      http.MethodPost,
			Template:    managerFirewallSectionItemRouteTemplate,
			Action:      "revise",
			Handler:     r.handleManagerFirewallSectionRevise(),
			RequireAuth: true,
		},
		{
			Name:        "manager.firewall.sections.list_with_rules",
			Method:      http.MethodPost,
			Template:    managerFirewallSectionItemRouteTemplate,
			Action:      "list_with_rules",
			Handler:     r.handleManagerFirewallSectionListWithRules(),
			RequireAuth: true,
		},
		{
			Name:        "manager.firewall.sections.update_with_rules",
			Method:      http.MethodPost,
			Template:    managerFirewallSectionItemRouteTemplate,
			Action:      "update_with_rules",
			Handler:     r.handleManagerFirewallSectionUpdateWithRules("update_with_rules"),
			RequireAuth: true,
		},
		{
			Name:        "manager.firewall.sections.revise_with_rules",
			Method:      http.MethodPost,
			Template:    managerFirewallSectionItemRouteTemplate,
			Action:      "revise_with_rules",
			Handler:     r.handleManagerFirewallSectionUpdateWithRules("revise_with_rules"),
			RequireAuth: true,
		},
		{
			Name:        "manager.firewall.rules.list",
			Method:      http.MethodGet,
			Template:    managerFirewallRulesRouteTemplate,
			Handler:     r.handleManagerFirewallRuleList(),
			RequireAuth: true,
		},
		{
			Name:        "manager.firewall.rules.create",
			Method:      http.MethodPost,
			Template:    managerFirewallRulesRouteTemplate,
			Handler:     r.handleManagerFirewallRuleCreate(),
			RequireAuth: true,
		},
		{
			Name:        "manager.firewall.rules.create_multiple",
			Method:      http.MethodPost,
			Template:    managerFirewallRulesRouteTemplate,
			Action:      "create_multiple",
			Handler:     r.handleManagerFirewallRuleCreateMultiple(),
			RequireAuth: true,
		},
		{
			Name:        "manager.firewall.rules.stats",
			Method:      http.MethodGet,
			Template:    managerFirewallRuleStatsRouteTemplate,
			Handler:     r.handleManagerFirewallRuleStats(),
			RequireAuth: true,
		},
		{
			Name:        "manager.firewall.rules.get",
			Method:      http.MethodGet,
			Template:    managerFirewallRuleItemRouteTemplate,
			Handler:     r.handleManagerFirewallRuleGet(),
			RequireAuth: true,
		},
		{
			Name:        "manager.firewall.rules.update",
			Method:      http.MethodPut,
			Template:    managerFirewallRuleItemRouteTemplate,
			Handler:     r.handleManagerFirewallRuleUpdate(),
			RequireAuth: true,
		},
		{
			Name:        "manager.firewall.rules.delete",
			Method:      http.MethodDelete,
			Template:    managerFirewallRuleItemRouteTemplate,
			Handler:     r.handleManagerFirewallRuleDelete(),
			RequireAuth: true,
		},
		{
			Name:        "manager.firewall.rules.revise",
			Method:      http.MethodPost,
			Template:    managerFirewallRuleItemRouteTemplate,
			Action:      "revise",
			Handler:     r.handleManagerFirewallRuleRevise(),
			RequireAuth: true,
		},
		{
			Name:        "manager.ip_sets.list",
			Method:      http.MethodGet,
			Template:    managerIPSetsRouteTemplate,
			Handler:     r.handleManagerIPSetList(),
			RequireAuth: true,
		},
		{
			Name:        "manager.ip_sets.create",
			Method:      http.MethodPost,
			Template:    managerIPSetsRouteTemplate,
			Handler:     r.handleManagerIPSetCreate(),
			RequireAuth: true,
		},
		{
			Name:        "manager.ip_sets.get",
			Method:      http.MethodGet,
			Template:    managerIPSetItemRouteTemplate,
			Handler:     r.handleManagerIPSetGet(),
			RequireAuth: true,
		},
		{
			Name:        "manager.ip_sets.update",
			Method:      http.MethodPut,
			Template:    managerIPSetItemRouteTemplate,
			Handler:     r.handleManagerIPSetUpdate(),
			RequireAuth: true,
		},
		{
			Name:        "manager.ip_sets.delete",
			Method:      http.MethodDelete,
			Template:    managerIPSetItemRouteTemplate,
			Handler:     r.handleManagerIPSetDelete(),
			RequireAuth: true,
		},
		{
			Name:        "manager.ip_sets.add_ip",
			Method:      http.MethodPost,
			Template:    managerIPSetItemRouteTemplate,
			Action:      "add_ip",
			Handler:     r.handleManagerIPSetMemberAction("add_ip"),
			RequireAuth: true,
		},
		{
			Name:        "manager.ip_sets.remove_ip",
			Method:      http.MethodPost,
			Template:    managerIPSetItemRouteTemplate,
			Action:      "remove_ip",
			Handler:     r.handleManagerIPSetMemberAction("remove_ip"),
			RequireAuth: true,
		},
		{
			Name:        "manager.ip_sets.members",
			Method:      http.MethodGet,
			Template:    managerIPSetMembersRouteTemplate,
			Handler:     r.handleManagerIPSetMembers(),
			RequireAuth: true,
		},
	}
}
